version: '3'

services:
  etcd:
    image: registry.cn-hangzhou.aliyuncs.com/coreos_etcd/etcd:v3
#    image: quay.io/coreos/etcd:v3.3
    container_name: etcd
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      ETCDCTL_API: 3
    volumes:
      - /tmp/etcd/etcd-data:/etcd-data
    command:
      - "/usr/local/bin/etcd"
      - "--name"
      - "etcd0"
      - "--data-dir"
      - "/etcd-data"
      - "--advertise-client-urls"
      - "http://0.0.0.0:2379"
      - "--listen-client-urls"
      - "http://0.0.0.0:2379"
      - "--initial-advertise-peer-urls"
      - "http://0.0.0.0:2380"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-cluster-token"
      - "docker-etcd"
      - "--initial-cluster"
      - "etcd0=http://0.0.0.0:2380"
      - "--initial-cluster-state"
      - "new"

  coredns:
    image: coredns/coredns:1.5.0
    container_name: coredns
    restart: always
    expose:
      - '53'
      - '53/udp'
    ports:
      - "53:53"
      - "53:53/udp"
    command: -conf /etc/coredns/Corefile
    volumes:
      - ./conf/Corefile:/etc/coredns/Corefile
    links:
      - etcd
